import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { cn } from "@/lib/utils";
import { StepsProvider } from "@/context/StepsContext";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StepsProvider>
        <body className={cn(inter.className, "flex min-w-screen")}>
          <SideBar />
          {children}
          <Toaster />
        </body>
      </StepsProvider>
    </html>
  );
}
